# Generated by Django 4.2.4 on 2023-08-14 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_hashtag_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hashtag',
            name='num',
        ),
    ]
