# Generated by Django 4.2.3 on 2023-08-16 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_photo'),
        ('post', '0004_tag'),
    ]

    operations = [
    ]
