# Generated by Django 4.2.3 on 2023-08-16 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_merge_0004_photo_0004_tag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
