# Generated by Django 4.2.3 on 2023-08-17 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_delete_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.CharField(max_length=20, null=True, verbose_name='지역'),
        ),
    ]
