# Generated by Django 4.2.3 on 2023-08-14 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='keywords',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='keywords',
            field=models.ManyToManyField(to='mypage.hashtag'),
        ),
    ]
