
# Generated by Django 4.2.4 on 2023-08-15 08:53

# Generated by Django 4.2.3 on 2023-08-15 15:46



from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='nickname',
            field=models.CharField(default='디폴트_닉네임', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='travel_style',
            field=models.CharField(default='디폴트_여행_스타일', max_length=100),
        ),
    ]
